package security;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "segmento")
   private java.lang.String segmento;
   @org.kie.api.definition.type.Label(value = "codigo_producto")
   private java.lang.Integer codigo_producto;
   @org.kie.api.definition.type.Label(value = "cantidad_productos")
   private java.lang.Integer cantidad_productos;
   @org.kie.api.definition.type.Label(value = "meses_gracia")
   private java.lang.Integer meses_gracia;
   @org.kie.api.definition.type.Label(value = "deporte_altoRiesgo")
   private java.lang.String deporte_altoRiesgo;
   @org.kie.api.definition.type.Label(value = "remuneracion")
   private java.lang.Integer remuneracion;
   @org.kie.api.definition.type.Label(value = "prima")
   private java.lang.Integer prima;
   @org.kie.api.definition.type.Label(value = "sexo")
   private java.lang.String sexo;
   @org.kie.api.definition.type.Label(value = "edad_cliente")
   private java.lang.Integer edad_cliente;
   @org.kie.api.definition.type.Label(value = "peso_cliente")
   private java.lang.Integer peso_cliente;
   @org.kie.api.definition.type.Label(value = "altura_cliente")
   private java.lang.Integer altura_cliente;
   @org.kie.api.definition.type.Label(value = "imc_cliente")
   private java.lang.Integer imc_cliente;

   public Cliente()
   {
   }

   public java.lang.String getSegmento()
   {
      return this.segmento;
   }

   public void setSegmento(java.lang.String segmento)
   {
      this.segmento = segmento;
   }

   public java.lang.Integer getCodigo_producto()
   {
      return this.codigo_producto;
   }

   public void setCodigo_producto(java.lang.Integer codigo_producto)
   {
      this.codigo_producto = codigo_producto;
   }

   public java.lang.Integer getCantidad_productos()
   {
      return this.cantidad_productos;
   }

   public void setCantidad_productos(java.lang.Integer cantidad_productos)
   {
      this.cantidad_productos = cantidad_productos;
   }

   public java.lang.Integer getMeses_gracia()
   {
      return this.meses_gracia;
   }

   public void setMeses_gracia(java.lang.Integer meses_gracia)
   {
      this.meses_gracia = meses_gracia;
   }

   public java.lang.String getDeporte_altoRiesgo()
   {
      return this.deporte_altoRiesgo;
   }

   public void setDeporte_altoRiesgo(java.lang.String deporte_altoRiesgo)
   {
      this.deporte_altoRiesgo = deporte_altoRiesgo;
   }

   public java.lang.Integer getRemuneracion()
   {
      return this.remuneracion;
   }

   public void setRemuneracion(java.lang.Integer remuneracion)
   {
      this.remuneracion = remuneracion;
   }

   public java.lang.Integer getPrima()
   {
      return this.prima;
   }

   public void setPrima(java.lang.Integer prima)
   {
      this.prima = prima;
   }

   public java.lang.String getSexo()
   {
      return this.sexo;
   }

   public void setSexo(java.lang.String sexo)
   {
      this.sexo = sexo;
   }

   public java.lang.Integer getEdad_cliente()
   {
      return this.edad_cliente;
   }

   public void setEdad_cliente(java.lang.Integer edad_cliente)
   {
      this.edad_cliente = edad_cliente;
   }

   public java.lang.Integer getPeso_cliente()
   {
      return this.peso_cliente;
   }

   public void setPeso_cliente(java.lang.Integer peso_cliente)
   {
      this.peso_cliente = peso_cliente;
   }

   public java.lang.Integer getAltura_cliente()
   {
      return this.altura_cliente;
   }

   public void setAltura_cliente(java.lang.Integer altura_cliente)
   {
      this.altura_cliente = altura_cliente;
   }

   public java.lang.Integer getImc_cliente()
   {
      return this.imc_cliente;
   }

   public void setImc_cliente(java.lang.Integer imc_cliente)
   {
      this.imc_cliente = imc_cliente;
   }

   public Cliente(java.lang.String segmento,
         java.lang.Integer codigo_producto,
         java.lang.Integer cantidad_productos,
         java.lang.Integer meses_gracia,
         java.lang.String deporte_altoRiesgo,
         java.lang.Integer remuneracion, java.lang.Integer prima,
         java.lang.String sexo, java.lang.Integer edad_cliente,
         java.lang.Integer peso_cliente, java.lang.Integer altura_cliente,
         java.lang.Integer imc_cliente)
   {
      this.segmento = segmento;
      this.codigo_producto = codigo_producto;
      this.cantidad_productos = cantidad_productos;
      this.meses_gracia = meses_gracia;
      this.deporte_altoRiesgo = deporte_altoRiesgo;
      this.remuneracion = remuneracion;
      this.prima = prima;
      this.sexo = sexo;
      this.edad_cliente = edad_cliente;
      this.peso_cliente = peso_cliente;
      this.altura_cliente = altura_cliente;
      this.imc_cliente = imc_cliente;
   }

}